title: James Kim
description: Stuff that I come across and find interesting.
author: Tauseef Jamadar
email: jrossokim@gmail.com
github: https://github.com/jrossokim
about: I am a Technical Project Manager at <a href="https://www.optum.com" target="_blank">Optum</a> and a novice developer. I love working on new technologies.

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jrossokim"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/jrossokim"

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/

markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
